"""
05_prepare_kto_data.py — Build KTO Binary-Label Dataset

Strategy
--------
  DESIRABLE   (label=True)  : Correct solutions from train.jsonl
                               (answer already verified in 02_format_data.py)
  UNDESIRABLE (label=False) : Wrong completions generated by the SFT model
                               at high temperature (sampling K per problem)

If --sft-adapter is omitted (SFT not yet trained), we fall back to generating
synthetic wrong answers by corrupting the correct answer strings — useful for
a dry-run / pipeline test before the SFT checkpoint exists.

Output
------
  data/splits/kto_train.jsonl   — balanced binary-label dataset
  data/splits/kto_stats.json    — counts, λD, λU, balance ratio

Usage
-----
  # With SFT model (recommended — run AFTER 04_sft_train.sh):
  python scripts/05_prepare_kto_data.py --sft-adapter checkpoints/sft

  # Dry-run without SFT checkpoint:
  python scripts/05_prepare_kto_data.py --dry-run
"""
import argparse
import json
import os
import random
import re
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).parent.parent))
import config

random.seed(42)


# ─── Answer Extraction ────────────────────────────────────────────────────────

def extract_answer(text: str) -> str:
    """Pull answer from <answer>...</answer> tag, with fallback heuristics."""
    m = re.search(r"<answer>\s*(.*?)\s*</answer>", text, re.DOTALL)
    if m:
        return m.group(1).strip().replace(",", "")
    # Fallback: last number in the text
    nums = re.findall(r"-?\d+(?:\.\d+)?", text.replace(",", ""))
    return nums[-1] if nums else ""


def answers_match(pred: str, gt: str) -> bool:
    """Fuzzy numeric + string equality check."""
    pred = pred.strip().lower().replace(",", "")
    gt   = gt.strip().lower().replace(",", "")
    if pred == gt:
        return True
    try:
        return abs(float(pred) - float(gt)) < 0.01
    except ValueError:
        return False


# ─── Corrupt-answer fallback (dry-run) ────────────────────────────────────────

def corrupt_answer(completion: str, answer: str) -> str:
    """
    Produce a plausibly-wrong completion by replacing the answer with a nearby
    integer (±1 to ±10 offset, or swapped digits).  Used in dry-run mode only.
    """
    try:
        val = float(answer.replace(",", ""))
        offset = random.choice([-10, -5, -3, -2, -1, 1, 2, 3, 5, 10])
        wrong = str(int(val + offset))
    except ValueError:
        chars = list(answer)
        random.shuffle(chars)
        wrong = "".join(chars) if chars else "WRONG"

    corrupted = re.sub(
        r"<answer>.*?</answer>",
        f"<answer>{wrong}</answer>",
        completion,
        flags=re.DOTALL,
    )
    return corrupted


# ─── MLX model generation ─────────────────────────────────────────────────────

def generate_wrong_outputs(data: list[dict], adapter_path: str, n_per_problem: int = 3) -> list[dict]:
    """
    Use the SFT model to generate n_per_problem completions per problem.
    Return all completions that produce an INCORRECT final answer.
    """
    try:
        from mlx_lm import load, generate as mlx_generate
    except ImportError:
        raise ImportError(
            "mlx_lm is not installed. Install it with:\n"
            "  pip install mlx-lm\n"
            "Or run with --dry-run to skip model generation."
        )

    print(f"\n[mlx] Loading SFT model for wrong-output generation...")
    print(f"      Base model : {config.BASE_MODEL}")
    print(f"      Adapter    : {adapter_path}")
    model, tokenizer = load(config.BASE_MODEL, adapter_path=adapter_path)

    undesirable = []
    total = len(data)

    for i, ex in enumerate(data):
        gt_answer = ex.get("answer", "")
        prompt    = ex["prompt"]

        for attempt in range(n_per_problem * 2):          # oversample, then filter
            try:
                response = mlx_generate(
                    model,
                    tokenizer,
                    prompt=prompt,
                    max_tokens=config.SFT_MAX_SEQ_LEN,
                    temp=0.9,                             # high temp for diversity
                    verbose=False,
                )
                pred = extract_answer(response)
                if not answers_match(pred, gt_answer):   # wrong → undesirable
                    undesirable.append({
                        "prompt":     prompt,
                        "completion": response,
                        "label":      False,
                        "source":     ex.get("source", "unknown"),
                        "task":       ex.get("task", "unknown"),
                    })
                    if len([u for u in undesirable
                             if u["prompt"] == prompt]) >= n_per_problem:
                        break
            except Exception as e:
                print(f"  [warn] Generation error on example {i}: {e}")
                break

        if (i + 1) % 50 == 0 or i == total - 1:
            print(f"  [{i+1}/{total}] undesirable collected so far: {len(undesirable)}", end="\r")

    print(f"\n[mlx] Done. {len(undesirable)} undesirable examples generated.")
    return undesirable


# ─── Main ─────────────────────────────────────────────────────────────────────

def main(args):
    Path(config.DATA_SPLITS).mkdir(parents=True, exist_ok=True)
    train_path = Path(config.DATA_SPLITS) / "train.jsonl"

    if not train_path.exists():
        print(f"❌ {train_path} not found. Run 03_rule_filter.py first.")
        sys.exit(1)

    # ── Load correct solutions (all desirable) ────────────────────────────────
    print(f"Loading training data from {train_path}...")
    with open(train_path, "r", encoding="utf-8") as f:
        all_train = [json.loads(l) for l in f if l.strip()]
    print(f"  → {len(all_train)} total training examples")

    # Subsample for KTO data prep (to keep it manageable)
    if args.max_desirable and args.max_desirable < len(all_train):
        all_train = random.sample(all_train, args.max_desirable)
        print(f"  → Subsampled to {len(all_train)} examples (--max-desirable)")

    desirable = [
        {
            "prompt":     ex["prompt"],
            "completion": ex["completion"],
            "label":      True,
            "source":     ex.get("source", "unknown"),
            "task":       ex.get("task", "unknown"),
        }
        for ex in all_train
    ]
    print(f"  → {len(desirable)} desirable examples (correct solutions)")

    # ── Collect undesirable examples ──────────────────────────────────────────
    if args.dry_run:
        print("\n[dry-run] Generating synthetic wrong outputs via answer corruption...")
        undesirable = []
        for ex in all_train[:args.max_undesirable]:
            corrupted = corrupt_answer(ex["completion"], ex.get("answer", "0"))
            undesirable.append({
                "prompt":     ex["prompt"],
                "completion": corrupted,
                "label":      False,
                "source":     ex.get("source", "unknown"),
                "task":       ex.get("task", "unknown"),
            })
        print(f"  → {len(undesirable)} synthetic undesirable examples (corrupted answers)")
    else:
        # Filter data to only math tasks for undesirable generation
        # (rule-based ORM works reliably for math; QA tasks are harder to auto-judge)
        math_data = [ex for ex in all_train if ex.get("task") == "math"]
        n_problems = min(args.max_undesirable_problems, len(math_data))
        sample = random.sample(math_data, n_problems)
        print(f"\nGenerating wrong outputs for {n_problems} math problems "
              f"(K={args.n_wrong_per_problem} per problem)...")
        undesirable = generate_wrong_outputs(sample, args.sft_adapter, args.n_wrong_per_problem)
        # Cap to avoid extreme imbalance
        if args.max_undesirable and len(undesirable) > args.max_undesirable:
            undesirable = random.sample(undesirable, args.max_undesirable)
            print(f"  → Capped to {len(undesirable)} undesirable examples")

    # ── Balance and compute λD, λU ────────────────────────────────────────────
    n_d = len(desirable)
    n_u = len(undesirable)

    print(f"\nDataset before balancing: {n_d} desirable, {n_u} undesirable")

    if args.balance == "subsample":
        # Option A (KTO paper recommendation): subsample desirable to match undesirable
        # → use λD=λU=1.0 (simplest; paper proves this works when data is abundant)
        n_target = min(n_d, n_u * 3)   # keep up to 3:1 desirable:undesirable ratio
        if n_d > n_target:
            desirable = random.sample(desirable, n_target)
            n_d = n_target
        lambda_d = 1.0
        lambda_u = 1.0
    else:
        # Option B: keep all data, adjust λ weights (eq. 9 in KTO paper)
        lambda_u = 1.0
        lambda_d = round(1.5 * n_u / max(n_d, 1), 4) if n_d > 0 else 1.0
        # Ensure ratio ∈ [1.0, 1.5]
        ratio = lambda_d * n_d / (lambda_u * max(n_u, 1))
        print(f"  λD={lambda_d:.4f}, λU={lambda_u:.4f}  |  λD·nD/(λU·nU) = {ratio:.3f} (target: [1.0, 1.5])")

    combined = desirable + undesirable
    random.shuffle(combined)

    print(f"\nFinal dataset: {len(desirable)} desirable + {len(undesirable)} undesirable "
          f"= {len(combined)} total")

    # ── Save ──────────────────────────────────────────────────────────────────
    out_path = Path(config.DATA_SPLITS) / "kto_train.jsonl"
    with open(out_path, "w", encoding="utf-8") as f:
        for ex in combined:
            f.write(json.dumps(ex, ensure_ascii=False) + "\n")
    print(f"\n✅ KTO dataset saved to: {out_path}")

    # Save stats (used by training scripts to auto-set λD, λU)
    stats = {
        "n_desirable":   len(desirable),
        "n_undesirable": len(undesirable),
        "n_total":       len(combined),
        "lambda_d":      lambda_d,
        "lambda_u":      lambda_u,
        "balance_mode":  args.balance,
        "dry_run":       args.dry_run,
    }
    stats_path = Path(config.DATA_SPLITS) / "kto_stats.json"
    with open(stats_path, "w") as f:
        json.dump(stats, f, indent=2)
    print(f"   Stats saved to: {stats_path}")
    print(f"\n   λD = {lambda_d}  |  λU = {lambda_u}")
    print(f"\nNext: Run 05b_prm_train.py (optional) or 06b_kto_train_mlx.py")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Prepare KTO binary-label dataset")
    parser.add_argument(
        "--sft-adapter", default="checkpoints/sft",
        help="Path to SFT LoRA adapter. Used to generate wrong model outputs.",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Skip model generation; corrupt answers synthetically (for pipeline testing).",
    )
    parser.add_argument(
        "--n-wrong-per-problem", type=int, default=3,
        help="How many wrong outputs to collect per math problem (default: 3).",
    )
    parser.add_argument(
        "--max-desirable", type=int, default=40000,
        help="Max correct examples to include as desirable (default: 40000).",
    )
    parser.add_argument(
        "--max-undesirable", type=int, default=0,
        help="Max undesirable examples (0 = no cap).",
    )
    parser.add_argument(
        "--max-undesirable-problems", type=int, default=3000,
        help="Number of problems to sample wrong outputs from (default: 3000).",
    )
    parser.add_argument(
        "--balance", choices=["subsample", "lambda"], default="subsample",
        help="Balance strategy: 'subsample' (Option A, paper default) or "
             "'lambda' (Option B — adjust weights, keep all data).",
    )
    args = parser.parse_args()
    main(args)
